name: mycroft
adopt-info: mycroft

summary: Your AI personal assistant!
description: |

  Mycroft is a free and open-source intelligent personal assistant and
  knowledge navigator for Linux-based operating systems that uses a natural 
  language user interface. It is the world''s first fully open-source AI 
  voice assistant.
  
  Mycroft is named after a fictional computer from 1966 science fiction novel
  "The Moon Is a Harsh Mistress".
  
  Installing skills by voice seems to be broken for now, but you can use
  the `mycroft.msm` command to list, install, and remove skills.

license: MIT

assumes:
  - command-chain
  
base: core20
grade: stable
confinement: strict
compression: lzo

layout:
  /etc/mycroft/mycroft.conf:
    bind-file: $SNAP/etc/mycroft/mycroft.conf
  /usr/include:
    bind: $SNAP/usr/include
  /var/tmp:
    bind: $SNAP_COMMON/vartmp
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /opt/mycroft/skills:
    bind: $SNAP_COMMON/mycroft-data/skills

apps:
  mycroft:
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    command-chain:
      - bin/homeishome-launch  
    command: bin/mycroft-launch
    desktop: usr/share/applications/mycroft.desktop
    extensions:
      - gnome-3-38
    plugs:
    - audio-playback
    - audio-record
    - desktop
    - desktop-legacy
    - mount-observe
    - network
    - network-bind
    - pulseaudio
    - unity7
    - wayland
    - x11
    - alsa
    
    build-packages:
      - libasound2-dev
      - libpcre2-dev

parts:

  desktop-file:
    build-packages: []
    organize:
      mycroft.desktop: usr/share/applications/mycroft.desktop
      mycroft.png: usr/share/icons/mycroft.png
    plugin: dump
    source: desktop
    stage-packages: []
    
  mimic:
    mimic:
    after:
      - snapcraft-preload
    build-packages:
      - libpcre2-dev
      - portaudio19-dev
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --disable-static
    prime:
      - usr/bin
      - usr/include
      - usr/lib
      - -usr/lib/*.a
      - -usr/lib/*.la
      - -usr/lib/pkgconfig
      - usr/share/mimic
    source: https://github.com/MycroftAI/mimic.git
    source-depth: 1
    source-type: git
    stage-packages:
      - libpcre2-8-0
  mycroft:
    after:
    - snapcraft-preload
    build-packages:
    - rsync
    override-build: 'mkdir -p $SNAPCRAFT_PART_INSTALL/mycroft-source
      rsync -a --exclude .git ./ $SNAPCRAFT_PART_INSTALL/mycroft-source/
      # Remove the mycroft-core folder
      rm -rf /root/project/mycroft-core
      '
    override-pull: '# Try to fetch mycroft-core
    git clone https://github.com/mycroftai/mycroft-core /root/project/mycroft-core 2> /dev/null || true
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed -e ''s|release/v||'')"
      sed -i ''s|/var/log/mycroft|$SNAP_USER_COMMON/logs|g'' start-mycroft.sh
      cat > scripts/prepare-msm.sh <<EOF
      #!/bin/sh
      true
      EOF
      sed -E -i ''s|(python3 -m \$\{_module\} \$_params)|$SNAP/bin/snapcraft-preload
      \1|g'' start-mycroft.sh
      '
    plugin: nil
    source: ./mycroft-core
    source-type: local
    stage-packages: []
  mycroft-conf:
    build-packages: []
    override-build: 'install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc/mycroft mycroft.conf
      '
    override-pull: "cat  > mycroft.conf <<EOF\n{\n    \"enclosure\": {\n        \"\
      update\": \"false\"\n    },\n    \"data_dir\": \"~/../common/mycroft-data\"\
      ,\n    \"log_dir\": \"~/../common/logs\"\
      ,\n    \"play_ogg_cmdline\": \"vlc --intf dummy --play-and-exit %1\"}\nEOF\n"
    plugin: nil
    stage-packages:
    - libfann-dev
  precise:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl -LOJ $(curl https://raw.githubusercontent.com/MycroftAI/precise-data/dist/x86_64/latest)
      curl -OJ https://raw.githubusercontent.com/MycroftAI/precise-data/models/hey-mycroft.tar.gz
    override-build: |
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/precise precise-engine_*.tar.gz
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/precise hey-mycroft.tar.gz
  mycroft-deps:
    after:
    - mimic
    - snapcraft-preload
    build-packages: []
    organize:
      usr/bin/mpg123.bin: usr/bin/mpg123
      usr/lib/*/*fann*.so*: usr/lib/
    override-build: "snapcraftctl build\nln -sf aclocal-1.15 $SNAPCRAFT_PART_INSTALL/usr/bin/aclocal\n\
      ln -sf automake-1.15 $SNAPCRAFT_PART_INSTALL/usr/bin/automake\nfor sofile in\
      \ libc.so libm.so libpthread.so; do\n    sed -Ei 's|(/usr/lib/$SNAPCRAFT_ARCH_TRIPLET)|/snap/mycroft/current\\\
      1|g' $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/$sofile\ndone\n"
    plugin: nil
    stage:
    - -usr/bin/sudo
    stage-packages:
    - yad
    - psmisc
    - autoconf
    - automake
    - binutils
    - bison
    - build-essential
    - cmake
    - coreutils
    - curl
    - flac
    - freeglut3
    - g++
    - gcc
    - git
    - jq
    - libportaudio2
    - libasound2
    - libasound2-plugins
    - libc++-dev
    - libc6-dev
    - libfann-dev
    - libffi-dev
    - libglib2.0-dev
    - libglu1-mesa
    - libgpm2
    - libicu-dev
    - libjack-jackd2-0
    - libjpeg-dev
    - libpcre2-dev
    - portaudio19-dev
    - libslang2
    - libssl-dev
    - libtool
    - libvlc-dev
    - make
    - mpg123
    - mplayer
    - pkg-config
    - procps
    - pulseaudio-utils
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python3-venv
    - rsync
    - screen
    - swig
    - vlc
    - zlib1g
  scripts:
    build-packages: []
    organize:
      mycroft-*: bin/
    plugin: dump
    source: scripts
    source-type: local
    stage:
    - bin/mycroft-*
    stage-packages: []
  snapcraft-preload:
    build-packages:
    - try:
      - gcc-multilib
      - g++-multilib
    plugin: cmake
    source: https://github.com/forslund/snapcraft-preload.git
    source-branch: no-as-needed
    stage-packages:
    - try:
      - lib32stdc++6      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch  
